#set math.equation(numbering: "(3.1)")

= The central charge and the Virasoro algebra

In this chapter, our goal is to construct the Hilbert space in CFT. we will introduce the Virasoro algebra, which is a central extension of the Witt algebra, also the building block of Hilbert space. The Virasoro algebra plays a crucial role in two-dimensional conformal field theories (CFTs) and string theory. We will also discuss the concept of the central charge, which can be used to distinguish different CFTs.

== Review of chapter 2
From now on and later, we only focus on two-dimensional CFTs. In chapter 2, we introduced the stress-energy tensor, its properties, definition of primary field and Ward identities. 

We also discussed the operator product expansion (OPE) of the stress-energy tensor, which leads to the definition of the central charge. The central charge is a key parameter in CFTs, and it characterizes the number of degrees of freedom in the theory. We also introduced the concept of primary fields and their correlation functions, which are essential for understanding the structure of CFTs.


== The free bosons
Here we review the basic properties of free bosons, which are the simplest example of CFTs. The free boson theory is described by a scalar field $phi(z, overline(z))$ with the action:
$ S = frac(1,4pi) integral d^2z partial phi(z, overline(z)) partial phi(z, overline(z)) $
The stress-energy tensor for the free boson theory can be derived from the action using the Noether procedure, and it is given by:
$ T(z) = -frac(1,2) :partial phi(z) partial phi(z): $
$ overline(T)(overline(z)) = -frac(1,2) :overline(partial) phi(overline(partial)) overline(partial) phi(overline(z)): $
The free boson theory has a central charge of $c = 1$.

== The free fermions
The free fermion theory is described by a fermionic field $psi(z)$ with the action:
$ S = frac(1,2pi) integral d^2z psi(z) overline(partial) psi(z) $
The stress-energy tensor for the free fermion theory can be derived from the action using the Noether procedure, and it is given by:
$ T(z) = -frac(1,2) :psi(z) partial psi(z): $
$ overline(T)(overline(z)) = -frac(1,2) :overline(partial) psi(overline(z)) overline(partial) psi(overline(z)): $
The free fermion theory has a central charge of $c = 1/2$.


== The central charge
The central charge, initially introduced in the context of $T T$ correlation's anomaly part:
$ T(omega)T(z) = frac(c/2, (z-omega)^4) + frac(2T(omega),(z-omega)^2) + frac(T'(omega),z-omega) $

similarly the anti-holographic stress-energy tensor $overline(T)$ has the same form with $overline(c)$.

== Mode expansion and the Virasoro algebra
The Virasoro algebra can be viewed as the Laurent expansion of the stress-energy tensor $T(z)$ in terms of its modes $L_n$:
$ T(z) = sum_(n=-infinity)^infinity L_n z^(-n-2) $

A naive dimensional analysis of the OPE of $T(z)T(w)$ leads to the commutation relations of the Virasoro algebra:
$ [L_m, L_n] = (m-n)L_(m+n) + frac(c, 12) m(m^2-1) delta_(m+n,0) $

== In- and out-states
The most important part of Hilbert space construction is to define vacuum states, from which we can generate the entire Hilbert space by applying the raising operators. From the perspective of QFT and interaction picture, the vacuum state is the asymptotic state at $t -> -infinity$ and $t ->  +infinity$, where the influence of the interacting fields vanishes. They are called the in-states and out-states, respectively. In CFT, we can also define the in- and out-states as the highest-weight states of the Virasoro algebra.

The in-states are 
$ |0_(text(i n)) chevron.r $

In CFT, we have two types of vacuum states: the in-states and the out-states. The in-states are defined as the states that are annihilated by all positive modes $L_n$ with $n > 0$, while the out-states are defined as the states that are annihilated by all negative modes $L_n$ with $n < 0$. The in- and out-states are also called the highest-weight states of the Virasoro algebra

the in- and out-states. We will see that the in- and out-states are defined as the highest-weight states of the Virasoro algebra, which are annihilated by all positive modes $L_n$ with $n > 0$. The highest-weight states are also called primary states, and they correspond to primary fields in the CFT. The descendants of the primary states are generated by acting with the negative modes $L_{-n}$ on the primary states, and they correspond to descendant fields in the CFT.

== Highest-weight states


== Descendants fields


== Duality and the bootstrap